language: ruby
rvm:
 - 2.3.3

addons:
  firefox: "47.0.1"

install:
  - bundle install
  - nvm install stable && nvm alias default stable
  - npm install npm@latest -g
  - npm --version
  - npm install

# https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUItime to start

script:
  - bundle exec rake spec
  - npm run test
