# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7ceb7436a37d7138a663f9f12c9320414902b774c55abc5bdde06314b339ffcf43bdd56baefc9a97c4416e68d754f58eae050049bccf80b3cbdc1695dae5704e

test:
  secret_key_base: 0774025ea382166d127ced7016d877971d6ae652837dbb9421275bf2cb5d10163a4f3cae8cc2ddd6dc44e2ab377da7ebcf8376438bf9f99ce2fc21c46927e688

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
